---
deployment:
  tasks:
    - export DEPLOYPATH=/home/mashacor/globalcargoec.mashacorp.com/
    - /bin/cp -R assets/ $DEPLOYPATH
    - /bin/cp -R forms/ $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp inner-page.php $DEPLOYPATH
    - /bin/cp portfolio-details.php $DEPLOYPATH